name: Execution of Get products
run-name: Search products Kabum

on:
  # schedule:
  #   - cron: '26 15 * * *' # Todos os dias ás 12:26
  workflow_dispatch:

jobs:
  products:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: echo "$ENV" > .env
        name: create .env
        shell: bash
        env:
          ENV: ${{secrets.ENV}}

      - run: pip install --upgrade pip setuptools wheel
        name: upgrade tools
            
      - run: poetry install
        name: install requirements with poetry
      
      - run: poetry run python3 -m robot -d .\report\ .\src\price.robot
        name: exec script
